### ISSUE TITLE
Audio Quality Completely Broken

### ISSUE THREAD

**Issue by wowitsjack** [facebookresearch/demucs#102]
Hi!

Just reinstalled macOS on my laptop, and upon reinstalling `demucs` and splitting one of my favourite songs to test, I was shocked to hear that `demucs` now outputs terrible quality spits with bleed from other instruments permeating every single split.

Previously splits were almost perfect, with zero instrument leak.

What has happened?

Can we have the old models back?

**Comment by adefossez** [comment]
@wowitsjack , Thanks for the report.
Indeed, I did some experiments with quantized models and it seemed like they were working fine in terms of metrics and when I had a quick listen but true there is more leakage.
So I have deactivated the quantized model by default. If you pull from master it should work like before :) Sorry for the inconvenience!

**Comment by adefossez** [comment]
So I found out the problem, a little mistake appeared between my early experiments with quantization and the models I released... So now I think the quantized models are almost on par with the complete version.
I am not activating them by default though, because from the metrics, perf is a bit worse for vocals and others.
