### ISSUE TITLE
Audio Still Broken.

### ISSUE THREAD

**Issue by wowitsjack** [facebookresearch/demucs#104]
Hi again!

After the recent reversion to the previous state of models, the issue is still not fixed.

Split qualiy has dramatically decreased and consistent audio leakage is still present. Please observe the following two splits of the same MP3.

One from the **OLD** demucs version, and one from the newer version.

As you can hear, the models from before time the serialization format change are vastly, vastly superior.

What has happened?

**Comment by adefossez** [comment]
Hey @wowitsjack , sorry you are still experiencing issue. I don't see the two splits of the mp3s you mention. If you find a way to share them (along with the original mixture) that would be super useful to debug the issue :)
The sha256 of the sum for the default (unquantized) model has not changed since january so the model would still be exactly the same. Did you check if you used the same version (demucs_extra vs demucs) as before?

**Comment by adefossez** [comment]
Actually nevermind, I have the audio in the email notification, just not here, I will check them out and update.

**Comment by adefossez** [comment]
Actually, I can't access the Dropbox link I received!

**Comment by dr-benway** [comment]
any updates regarding this issue ?
ever since the (early April) update I, too, reverted to using previous version, as the separation accuracy is far superior ... (well .. day & night methinks ...)

**Comment by adefossez** [comment]
@dr-benway there should be no difference anymore. Make sure your repo is up-to-date. If the problem persist you can use the early April version by doing:
```
git checkout 8b1f683290f24c170910a4fa8987cd13c439c8e5
```
and then it will work as before. If you have a track on which you hear a clear difference, just let me know the artist and title and I'll look into it.

**Comment by dr-benway** [comment]
cheers ! will do as soon as I can && I will let you know.

**Comment by dr-benway** [comment]
@adefossez thanks so much !
tis all a ok now 👍

**Comment by adefossez** [comment]
Awesome, thanks for letting me know
