### ISSUE TITLE
[Question] Is there a way to output as another file format?

### ISSUE THREAD

**Issue by S10MC2015** [facebookresearch/demucs#105]
Hello,
I was wondering if there was a way to get demucs to output the .wav or convert them to another file format like .mp3?

Sorry for asking.
Thanks

**Comment by adefossez** [comment]
Hey, I haven't added that option, but I think I could easily add support mp3 in 320kbit/s mode if the ffmpeg installation support it.

**Comment by adefossez** [comment]
So I looked a bit into that. The default ffmpeg installation supports very little formats as export, and because it depends on so many factors (libraries installed, OS etc), it would be hard to make any assumption on its capabilities.
So I decided to only add support for mp3 with 320 kb/s rate, which should cover most needs. You need to install the lame encoder and then you can pass the `--mp3` flag and it will automatically transcode to mp3:
```bash
conda install lame
python.exe -m demucs.separate --dl --mp3 PATH_TO_AUDIO_FILE
```
Just pull from master and hopefully this should work, let me know if you have any trouble.

**Comment by S10MC2015** [comment]
thank you. Ill try it in a bit

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/79394561-b26ff300-7f6f-11ea-90bf-a15c01b69595.png)
In the output directory, there was only drums.wav.
This happened when using demucs -Q

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/79395905-9883df80-7f72-11ea-9872-b8f08ce947f6.png)
welp

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/79396061-003a2a80-7f73-11ea-923e-0b35b5bf79db.png)
it is doing something

**Comment by S10MC2015** [comment]
hmm seems like lame didn't install properly. my bad

**Comment by adefossez** [comment]
Thanks for the report ! Yes the `-Q` version is just to have faster download of the models. I'm going to see if there is an easy way to get lame on windows.
It is possible other software bundle lame along but then it would kind of hard to find it as it could be stored in a non standard location.

**Comment by adefossez** [comment]
Hello @S10MC2015 , I've found a python package that bundle the lame encoder that is also available on Windows. When you have some time, could you pull from master and try the following commands? That would be super helpful :)
```bash
python.exe -m pip install -U lameenc
python.exe -m demucs.separate --dl --mp3 PATH_TO_AUDIO_FILE
```

**Comment by S10MC2015** [comment]
It works.

**Comment by S10MC2015** [comment]
Thank you.
