### ISSUE TITLE
When I try to put the commands the output is this

### ISSUE THREAD

**Issue by crivuw** [facebookresearch/demucs#12]
I managed to "install" the code files and all of that. When I try the first command, this one.
### 

> python.exe -m demucs.separate --dl -n demucs PATH_TO_AUDIO_FILE_1

I get this
![error](https://user-images.githubusercontent.com/58601077/70334701-34c00c00-1846-11ea-96c9-55de939d49ed.png)

Im on windows 10 64 bit

**Comment by adefossez** [comment]
You need to run the command from a shell, not from ipython. Not sure how to get it started on Windows though.

**Comment by JettoDz** [comment]
I'm on Windows too, and likely due the same ytber.

First, run the command from Anaconda powershell or Anaconda promt. You can find them in the Start Menu, Anaconda3 submenu. To know if you have demucs activated, your promt should have "(demucs)" at the begining. If instead of 'demucs' it says 'base', then run `conda activate demucs`

There is where you need to run the code to separate the tracks, but it may give you a "ModuleNotFoundError". If that's the case, you need to get into the folder where demucs' files are. In my case, I downloaded and plopped the demucs-master files in my C:\Users\Jetto\ folder. The Anaconda promt is in that same path, so I run the command `cd demucs-master` to get into the folder. From there, the `python.exe -m demucs.separate -dll -n demucs PATH_TO_FILE` can run.

... Now, it MAY give another error, regarding an Intel dll. The mkl_intel_thread.dll, to be specific. There are some ways to fix it, but the one I used was to run the command `set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1`. It did the trick and the demucs.separate finally worked. I don't know how elegant this particular solution is, but I'm new into this as well.

I guess this is what happens when a bunch of us, Windows mortals, dwelve into github without much idea haha.

**Comment by adefossez** [comment]
@JettoDz , thanks for the trick for solving `mkl_intel_thread.dll`, I have added it to the readme.

@crivuw I have updated the README with more detailed instructions for Windows: https://github.com/facebookresearch/demucs/blob/master/README.md#using-windows
I hope this help!
