### ISSUE TITLE
How to do unlabeled data remixing

### ISSUE THREAD

**Issue by Ryuklear** [facebookresearch/demucs#273]
## ❓ Questions

In the paper, "Demucs: Deep Extractor for Music Sources with extra unlabeled data remixed", you proposed the use of
the extracted data for training. Where is the code to run?

**Comment by adefossez** [comment]
Hello @Ryuklear , the code for the paper you mentioned was never released. It was a first work I did on source separation, and while it worked nicely when training on short extracts, it didnt scale when training on 10 seconds extracts (because of the difficulty of reliably finding such long samples in unsupervised data). I later focused on other changes as mentioned in the "Music Source Separation in the Waveform Domain" which is the paper for which I released code (and now the "Hybrid Spectrogram and Waveform Source Separation" paper) .

**Comment by Ryuklear** [comment]
Thank you so much for the information! I was inspired by the method you mentioned in the papar, so I've been working on silent sources detector based on Sound Event Detection (SED). I'm new to the field of Source Separation and SED, so I have no idea that this would work for demucs. What do you think of my idea?

**Comment by adefossez** [comment]
one difficulty as I said is that you need to get a really good accuracy on your detection. Then you need to easily find long segments without one of the sources, which might not be there. or train efficiently on shorter segments (but with Demucs, the extra unlabeled data did not compensate for the shorter segments, although I could have tried more complex things like glueing short segments together). And the last issue is that the `other` source is always present in music, so you can never get samples without it. It is possible that with a better silent source detector you might get good results, but it would require quite a bit of work to test it with Demucs, and the code i used at the time is now seriously outdated.

**Comment by Ryuklear** [comment]
Ok, It needs to be examined properly. Thank you again!

**Comment by adefossez** [comment]
I'll be closing the issue now, feel free to open another one for future questions.
