### ISSUE TITLE
Installing Demucs Locally?

### ISSUE THREAD

**Issue by KirbysAdventureMusic** [facebookresearch/demucs#279]
## ❓ Questions

I genuinely have no idea what I'm doing wrong. I don't have any Python experience, I just want to be able to run Demucs locally (I do have a GPU). Off the top of my head:
* I've installed python
* I've installed the anaconda prompt
* I've installed the github desktop client
* I've downloaded/installed pytorch
* I've run `python.exe -m pip install -U demucs`

However, none of the following from the Windows support page work:
```
cd %HOMEPATH%
git clone -b main --single-branch https://github.com/facebookresearch/demucs ./demucs
```
"'git' is not recognized as an internal or external command, operable program or batch file."
`cd ./demucs`
"The system cannot find the path specified."
`conda env update -f environment-cpu.yml`
EnvironmentFileNotFound: 'C:\Users\Upstairs\environment-cpu.yml' file not found
`conda activate demucs`
"Could not find conda environment: demucs. You can list all discoverable environments with `conda info --envs`."
`python.exe -m pip install -e .`
"ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Users\Upstairs"

What am I doing wrong? Is there something I need to do to get Github to interface with the anaconda prompt?

**Comment by thesinepainter** [comment]
Hey, here's a beginner's guide to installing demucs locally from source:

Step 1
Open Anaconda Prompt


Step 2
Create a conda environment for demucs using:
`conda create --name demucs`

Type `y` when prompted to proceed.


Step 3
Activate the environment with:
`conda activate demucs`


Step 4
Install Pytorch for CUDA using:
`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`


Step 5
Since you're interested in only running the code, no need to bother with the `git` command or GitHub desktop. 
Just download and extract the `demucs-main`  zip from the `Code` dropdown on the main page:
![Demucs-1](https://user-images.githubusercontent.com/54241101/150653655-99aa927e-546b-48fa-bf2f-c057a0ef2b70.jpg)



Step 6
Install `demucs` by entering the following in the anaconda prompt window:
`pip install -e "PATH_TO_demucs-main"`

Where PATH_TO_demucs-main is your path to the extracted `demucs-main` folder, so the final command might look like:
`pip install -e "C:\Users\username\Documents\demucs-main"`


Step 7
Install PySoundFile audio backend using:
`pip install PySoundFile`

That's it, you're all setup!  

Step 8
Test if everything is running using:
`demucs -d cuda -o PATH_TO_OUTPUT_DIRECTORY PATH_TO_AUDIO_FILE`

Now, whenever you want to run demucs:
>Open Anaconda Prompt - Step 1
Activate demucs environment - Step 3 
>Run `demucs` command - Step 8

Note: Usually you would use the .yml file to automatically create the environment and download all dependencies, but for some reason, `environment-cuda.yml` kept downloading the cpu version of pytorch, so I had to create the environment and install pytorch manually.

**Comment by KirbysAdventureMusic** [comment]
Thank you so much! Sadly, I'm still getting technical errors, though.
When installing cuda and pytorch (4):
"SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)'))"

When installing demucs (6):
"'pip' is not recognized as an internal or external command, operable program or batch file."

**Comment by thesinepainter** [comment]
No worries, never got that error myself. Could you try running Anaconda Prompt as administrator? If that doesn't work maybe reinstalling Anaconda might help.
https://www.anaconda.com/products/individual

There are also some solutions here:
https://stackoverflow.com/questions/33699577/conda-update-fails-with-ssl-error-certificate-verify-failed

**Comment by KirbysAdventureMusic** [comment]
I'll either tackle this another day or wait until somebody creates an installation package/GUI. I still can't get it to work.

**Comment by KirbysAdventureMusic** [comment]
So, it turns out I was massively overcomplicating things! Since I had already run `python.exe -m pip install -U demucs` and `pip install PySoundFile`, all I needed to do was give it something to split - the Windows support page is irrelevant.
Maybe this could be made clearer in the readme?

(Thanks again for your help, thesinepainter!)

**Comment by thesinepainter** [comment]
I'm glad you got it working with just the pip install! I couldn't get pip to install the cuda version of pytorch so I had to do it manually (maybe it was because I was running it inside conda). Anyway since you've got all the required libraries, if you wanted the latest features, you could also try installing from source using `python.exe -m pip install -e "PATH_TO_demucs-main"` from wherever you run demucs. Worst case, it doesn't build and nothing happens, best case it upgrades demucs to the latest version.
And yeah I agree, the installation documentation isn't clearly laid out and could be reworked.
Cheers!

**Comment by CarlGao4** [comment]
@thesinepainter you can't install cuda version with conda is normal. Since conda version of pytorch is huge(2.4GiB), the developers didn't upload them onto PyPi or Conda repository. What you need to is uninstalling torch and torchaudio, then visit [PyTorch website](https://pytorch.org/get-started/locally) and follow their instructions.
