### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by inagoy** [facebookresearch/demucs#318]
> Executor: Starting 1 worker processes for DDP.
> [04-08 02:55:33][demucs.train][INFO] - For logs, checkpoints and samples check /content/demucs/outputs/xps/6a7f8677
> [04-08 02:55:33][dora.distrib][INFO] - world_size is 1, skipping init.
> [04-08 02:55:36][demucs.train][WARNING] - No vocal source found
> [04-08 02:55:36][demucs.train][INFO] - train/valid set size: 8 4
> [04-08 02:55:36][demucs.solver][INFO] - ----------------------------------------------------------------------
> [04-08 02:55:36][demucs.solver][INFO] - Training...
> Error executing job with overrides: ['dset=prueba']
> Traceback (most recent call last):
>   File "/content/demucs/demucs/train.py", line 149, in main
>     solver.train()
>   File "/content/demucs/demucs/solver.py", line 195, in train
>     metrics['train'] = self._run_one_epoch(epoch)
>   File "/content/demucs/demucs/solver.py", line 404, in _run_one_epoch
>     return distrib.average(losses, idx + 1)
> UnboundLocalError: local variable 'losses' referenced before assignment
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> Executor: Worker 0 died, killing all workers

I'm trying to train with a small drums dataset, to get demucs working. But i'm getting this error
I followed the advice provided here [221](https://github.com/facebookresearch/demucs/issues/221)

**Comment by inagoy** [comment]
Sorry I really don't remember how, but i got it working.
I can tell you the steps that worked for me, trained on Colab: 
-Git clone the repo
-!pip install -r requirements.txt
-!pip install -e .
-!sudo apt-get install soundstretch 
!dora run dset= <your_dataset>

My dataset setup: 

> dset:
>   wav: <path>
>   samplerate: 44100
>   channels: 2
>   segment: 8 (reduced segment so GPU can handle it)
>   sources: ['source1','source2','source3','source4']
> epochs: 120
> batch_size: 4   (reduced batch size)
> augment:      (no augment)
>   shift_same: false
>   scale:
>     proba: 0
>   remix:
>     proba: 0
>   repitch:
>     proba: 0

**Comment by xavriley** [comment]
Thanks for the quick reply. I think I figured this out.

For anyone else looking to train from scratch, MUSDB18HQ only has `test` and `train` folders but the `get_wav_datasets()` function (recommended for custom datasets) expects a `train` folder and a `valid` folder.

I tried renaming the folder but it wasn't picked up at first because the config file here https://github.com/facebookresearch/demucs/blob/main/demucs/wav.py#L182 already existed. Setting a breakpoint and writing it manually worked for me, but I imagine deleting the file and allowing it to be recreated would work too.

If this works you should see

```
[demucs.train][INFO] - train/valid set size: 141304 96
```

whereas before I was seeing 

```
[demucs.train][INFO] - train/valid set size: 141304 0
```

and it failed with the error above.

**Comment by ALEXander22568** [comment]
@xavriley I have same problem, but I cannot figure it out even follow your advice. I have a really poor skill in Python.

**Comment by jie-chen** [comment]
This only happens to me with parameter  -f 955717e8 added. Should we use default config to train?
