### ISSUE TITLE
Speeding up the process on Apple Silicon M1 Max

### ISSUE THREAD

**Issue by Fregggy** [facebookresearch/demucs#432]
I'm running this on an M1 Max 64 GB and it's only running at 2 seconds. Is there any way to boost this?

**Comment by matiaszanolli** [comment]
The big issue here is that the current stable version of Pytorch (the machine learning framework behind Demucs) only supports recent NVIDIA GPUs with CUDA support, so that pretty much leaves GPU support out of the table.

Entering PyTorch 2.0. Though it's still in beta stage it's really robust and can help improve speed and compatibility in many cases. Talking specifically about GPUs, PyTorch 2.0 can make use of Triton, a neuroscience API equivalent to CUDA in many forms (though even better implemented) and compatible with mostly every GPU recently released, Apple included.

You can give my fork a try, I haven't tried it on Apple hardware and probably the code still needs some adjustments to be done (I still didn't have time to find out if I need to handle the switch between Triton and CUDA or it will handle itself) but hopefully you'll be able to work with GPU (CPU performance should be improved from this anyway)

So, here's the fork:
**[https://github.com/matiaszanolli/demucs](https://github.com/matiaszanolli/demucs)**

The install procedure is pretty straightforward:

- Install the requirements (from requirements.txt, Conda can give some issues regarding CUDA)
- Remove `torch` and `torchaudio` and install them using the command `pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu` (I'm working this fork specially for CUDA, sorry)
- Finally install demucs launching `pip3 install -e .` from demucs root folder. This should replace your current Demucs installation with mine based on PyTorch 2.0.

Please let me know if you find any issues during the process or while working with it. You can always can revert to the original library if this one doesn't work for you, but any feedback you may have would be more than appreciated.

**Comment by matiaszanolli** [comment]
> > I'm running this on an M1 Max 64 GB and it's only running at 2 seconds. Is there any way to boost this?
> 
> Would you be willing to set up a Parallels partition/virtual environment, install Windows10 for ARM etc, install Demucs, and see how it performs under an emulated Windows environment running on an M(x) Mac? I'm curious about this myself. Ive seen some videos that the ARM processors can compete on emulated Windows tasks, with a real PC with similar specs.
> 
> If youre willing to try this and report back to us I'd love to hear about it.

Actually I had run that test with Pytorch 1.13 using AWS Graviton CPUs (Amazon's own flavor of ARM). There should be not much of a difference with M1 processors while you stick purely to CPU processing. I saw a really small increase on performance (around 10%) compared with standard Intel-based instances with the same amount of vCPUs, but it's not that much to call it a real difference in the performance side (though it lowers server costs a lot).

However, I'd really like to see M1 processors doing their thing from MacOS and see all native improvements in action, just to see how weel do these chips perform when programmed specifically for them (both on CPU and GPU environments).

Besides that, I'm

**Comment by berndverst** [comment]
I installed the `pytorch` nightly libraries and attempted to use `demucs` running on Metal (`-d mps`) (on an M2 Pro).

The problem is that Metal doesn't support certain data types.

Using these versions right now:
```
torch==2.0.0.dev20230211
torchaudio==2.0.0.dev20230211
torchvision==0.15.0.dev20230211
```

You can check that the Metal backend is working with pytorch:
```
torch.backends.mps.is_available()
```

Running `demucs --two-stems=vocals -d mps something.wav` will give you:

```bash
bverst@Bernds-Mac-mini Stems % demucs --two-stems=vocals -d mps something.wav
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /Users/bverst/Music/Stems/separated/htdemucs
Separating track something.wav
/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py:216: UserWarning: 0MPS: no support for int64 min/max ops, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1254.)
  weight = (weight / weight.max())**transition_power
  0%|                                                                                | 0.0/1351.35 [00:00<?, ?seconds/s]/opt/homebrew/lib/python3.10/site-packages/torch/functional.py:641: UserWarning: The operator 'aten::_fft_r2c' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
  0%|                                                                                | 0.0/1351.35 [00:01<?, ?seconds/s]
Traceback (most recent call last):
  File "/opt/homebrew/bin/demucs", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/separate.py", line 163, in main
    sources = apply_model(model, wav[None], device=args.device, shifts=args.shifts,
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 171, in apply_model
    out = apply_model(sub_model, mix, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 196, in apply_model
    shifted_out = apply_model(model, shifted, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 226, in apply_model
    chunk_out = future.result()
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/utils.py", line 129, in result
    return self.func(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 241, in apply_model
    out = model(padded_mix)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/htdemucs.py", line 628, in forward
    zout = self._mask(z, x)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/htdemucs.py", line 470, in _mask
    out = torch.view_as_complex(out.contiguous())
NotImplementedError: The operator 'aten::view_as_complex' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

Using the CPU fallback method `PYTORCH_ENABLE_MPS_FALLBACK=1` I get:

```bash
bverst@Bernds-Mac-mini Stems %  PYTORCH_ENABLE_MPS_FALLBACK=1 demucs --two-stems=vocals -d mps yerinbaeksongs.wav
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /Users/bverst/Music/Stems/separated/htdemucs
Separating track yerinbaeksongs.wav
/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py:216: UserWarning: 0MPS: no support for int64 min/max ops, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1254.)
  weight = (weight / weight.max())**transition_power
  0%|                                                                                | 0.0/1351.35 [00:00<?, ?seconds/s]/opt/homebrew/lib/python3.10/site-packages/torch/functional.py:641: UserWarning: The operator 'aten::_fft_r2c' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/opt/homebrew/lib/python3.10/site-packages/demucs/htdemucs.py:470: UserWarning: 0The operator aten::view_as_complex appears to be a view operator, but it has no implementation for the backend "mps:0". View operators don't support falling back to run on the CPU, since the tensor's storage cannot be shared across devices. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/CPUFallback.cpp:181.)
  out = torch.view_as_complex(out.contiguous())
  0%|                                                                                | 0.0/1351.35 [00:01<?, ?seconds/s]
Traceback (most recent call last):
  File "/opt/homebrew/bin/demucs", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/separate.py", line 163, in main
    sources = apply_model(model, wav[None], device=args.device, shifts=args.shifts,
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 171, in apply_model
    out = apply_model(sub_model, mix, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 196, in apply_model
    shifted_out = apply_model(model, shifted, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 226, in apply_model
    chunk_out = future.result()
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/utils.py", line 129, in result
    return self.func(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/apply.py", line 241, in apply_model
    out = model(padded_mix)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/htdemucs.py", line 633, in forward
    x = self._ispec(zout, training_length)
  File "/opt/homebrew/lib/python3.10/site-packages/demucs/htdemucs.py", line 444, in _ispec
    z = F.pad(z, (0, 0, 0, 1))
TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
```

So it seems that the demucs source uses data types that simply cannot work with Metal.

**Comment by berndverst** [comment]
Here is a relevant page from the pytorch docs
https://pytorch.org/docs/stable/notes/mps.html

I don't really work with PyTorch so I'm hoping someone can incorporate the necessary changes

**Comment by jpike88** [comment]
On an M1 Max, I saw my cpu hit 950% and add a heart attack. Turns out I have 10 cores!

How much faster would an M1 Max be with proper GPU support?

**Comment by CarlGao4** [comment]
I've read some issues about mps of pytorch, it turns out that currently mps doesn't support complex types (like 1+2j). But I think demucs requires complex types. One of the current solution is adding `a.to("cpu")` before the operations which are not supported and `a.to("mps")` after that. But I don't have Apple Silicon device, I can't test whether it works myself. Besides, once pytorch supported all these operations, these added codes should be removed.
