### ISSUE TITLE
musdb18HQ

### ISSUE THREAD

**Issue by DerryFitz** [facebookresearch/demucs#44]
Hi, 
I'm interested in retraining with the HQ version of musdb, and the ability to load this version of musdb would make a great addition to the project,
Thanks

**Comment by adefossez** [comment]
Hey DerryFitz :)
Indeed, it will be in any case useful to have support for custom datasets as well. Let me work on that and let you know when it is ready :)

**Comment by DerryFitz** [comment]
Great! Thanks, I'm looking forward to it

**Comment by james34602** [comment]
Hello researchers,
Will you guy train the network with the extra dataset used in Wave-U-Net, the CCMixter dataset.
However CCMixter may not provide All 4 outputs needed, only Vocal and Others could be trained.
I like to see the result Demucs separator and Wave-U-Net separator working on same, larger amount of datasets.

**Comment by YadChen** [comment]
Hi! 
I'm currently working on audio source separation and I'm interested in your article, but I can't get the MUSDB18HQ dataset, which has been bothering me for a long time. I'd appreciate it if you could help me.

**Comment by faroit** [comment]
@YadChen request here: https://zenodo.org/record/3338373

**Comment by YadChen** [comment]
Thanks!

**Comment by jaslineljy** [comment]
> Hey DerryFitz :)
> Indeed, it will be in any case useful to have support for custom datasets as well. Let me work on that and let you know when it is ready :)

Hi, may I know if you face a similar issue when you try to work on using the HQ dataset?:
>ValueError: num_samples should be a positive integer value, but got num_samples=0

 I was wondering if demucs actually allow us to run with `.wav` format or we can only use `.stempeg` / `.mp4` format? Does that mean custom datasets have to also be in `.stempeg` as well? Doesnt it mean that the decompressing will take up much more time? 
 
 If possible, it would be great if you could share when is ready :)

**Comment by faroit** [comment]
> > Hey DerryFitz :)
> > Indeed, it will be in any case useful to have support for custom datasets as well. Let me work on that and let you know when it is ready :)
> 
> Hi, may I know if you face a similar issue when you try to work on using the HQ dataset?:
> 
> > ValueError: num_samples should be a positive integer value, but got num_samples=0
> 
> I was wondering if demucs actually allow us to run with `.wav` format or we can only use `.stempeg` / `.mp4` format? Does that mean custom datasets have to also be in `.stempeg` as well? Doesnt it mean that the decompressing will take up much more time?
> 
> If possible, it would be great if you could share when is ready :)

MUSDB18HQ is in wav format

**Comment by jaslineljy** [comment]
Does that mean that Demucs can only run in mp4 stems format? There is no way for it to run the MUSDB18HQ `.wav` format  files is it? 
In that case, does that mean that custom datasets have to be in `.stempeg` in order to run Demucs?

Is there a way to allow it to run `.wav` files instead? This is because i see certain posts online mention that running on `.wav` is faster since there is lesser time spent on decompressing and it is also less noisy.  If i am wrong, feel free to correct me.

**Comment by jaslineljy** [comment]
> > > Hey DerryFitz :)
> > > Indeed, it will be in any case useful to have support for custom datasets as well. Let me work on that and let you know when it is ready :)
> > 
> > 
> > Hi, may I know if you face a similar issue when you try to work on using the HQ dataset?:
> > > ValueError: num_samples should be a positive integer value, but got num_samples=0
> > 
> > 
> > I was wondering if demucs actually allow us to run with `.wav` format or we can only use `.stempeg` / `.mp4` format? Does that mean custom datasets have to also be in `.stempeg` as well? Doesnt it mean that the decompressing will take up much more time?
> > If possible, it would be great if you could share when is ready :)
> 
> MUSDB18HQ is in wav format

Does that mean that Demucs can only run in mp4 stems format? There is no way for it to run the MUSDB18HQ .wav format files is it?
In that case, does that mean that custom datasets have to be in .stempeg in order to run Demucs?

Is there a way or any modification to the code so that it can allow the model to run .wav files instead? This is because I see certain posts online mention that running on .wav is faster since there is lesser time spent on decompressing and it is also less noisy. If i am wrong, feel free to correct me.

**Comment by adefossez** [comment]
At the moment Demucs can only run on the original musdb dataset a the moment. There is also support for the `raw` format, which could be hacked to work with Musdb18HQ format. The raw format expect a folder containing both a `train` and `valid` subfolder. Each folder should contain any number of files with the naming convention `file_name.{STEM_IDX}.raw` with `{STEM_IDX}` going from 0 to 5, 0 being the sum of all stems, and 1 to 5 the sources. Data needs to be pre-normalized.
This will use quite a bit of space (2x the original size of MusDBHQ as the data is stored as float32). 

You can generate raw training data with the following script. You will need to split yourself the tracks between train and valid before calling it. Then call this script with 3 arguments: 1) folder containing train tracks as wavs (each track in a subfolder with `[drums|bass|other|vocals].wav` files 2) folder containing valid tracks, same format 3) target folder. Then you can call Demucs with `--raw=RAW_FOLDER` and it will train on this. However, at the moment, evaluation will still be against the regular MusDB dataset (although I guess a simple `is_wav=True` when creating the `musdb.DB` instance might do the trick)

At the moment this is the only support I can provide, although making Demucs work with arbitrary datasets is on my todo list.

```python
#!/usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path
from shutil import rmtree

import tqdm
from demucs import audio


SOURCES = ["drums", "bass", "other", "vocals"]


def process(tracks, destination):
    destination.mkdir()
    for track in tqdm.tqdm(list(tracks.iterdir())):
        mix = 0
        sources = []
        for name in SOURCES:
            path = track / f"{name}.wav"
            source = audio.AudioFile(path).read(streams=0, channels=2)
            sources.append(source)
            mix += source
        mono = mix.mean(dim=0)
        mean = mono.mean()
        std = mono.std()
        sources.insert(0, mix)

        for index, wav in enumerate(sources):
            target = destination / f"{track.stem}.{index}.raw"
            wav = (wav - mean) / std
            open(target, "wb").write(wav.t().numpy().tobytes())


def main():
    parser = ArgumentParser("make_raws.py")
    parser.add_argument("train", type=Path)
    parser.add_argument("valid", type=Path)
    parser.add_argument("out", type=Path)

    args = parser.parse_args()
    if args.out.exists():
        rmtree(args.out)
    args.out.mkdir()

    print("Processing train")
    process(args.train, args.out / "train")
    print("Processing valid")
    process(args.train, args.out / "valid")


if __name__ == "__main__":
    main()
```

**Comment by jaslineljy** [comment]
Hi, @adefossez thanks so much for your help! I have a few other questions that might need your help in explaining.
1) Can I know what are the possible issues or advantages/ disadvantages that we will face if we use MUSDB18HQ (`.wav`) instead of MUSDB18 (`.stempeg`)? From what I roughly know, uncompress seems to take lesser time and has slightly more accurate results. But other than that I am not exactly sure. According to [Sigsep website](https://sigsep.github.io/datasets/musdb.html#musdb18-compressed-stems), it seems that the compressed MUSDB18 version does not really affect much in the results. Is that why it is actually fine to use it instead of MUSDB18HQ?
![image](https://user-images.githubusercontent.com/44189034/106241136-7bd64100-6240-11eb-995d-c3796904e91c.png)

2) In the Demucs paper, it mentions that there are other extra datasets. Do you have any idea where to get them? or whether it is also `.stempeg` format or `.raw` format. 

3) Just want to also confirm if `.flac` format dataset, can I treat it like MUSDB18 `.stempeg` format to run in Demucs model? This is because I would like to experiment it with selective Slakh2100 files. But I am not sure if Demucs is able to run `.flac` format. I do have the `.wav` format after conversion. But since Demucs does not support `.wav` i was wondering if `.flac` works. 

4) Since MUSDB18 is compressed using Native Instruments, is it possible if i download the Native instrument application and manually compress the STEM `.wav` format files into `.stempeg`? I have yet to try it out but do you think it works though it is time-consuming?

**Comment by jaslineljy** [comment]
just to confirm, if i were to use an arbitrary test set, does it have to be in the same format as MUSDB18 stempeg format? Or it can be in wav format? If the latter is possible, does it need a specific folder/file arrangement?

**Comment by jaslineljy** [comment]
hi, i got an error after trying to run the script with the 3 arguments
>>from utils import temp_filenames
ModuleNotFoundError: No module named 'utils'

after i pip install utils, i run the script again and i got an error 
>>from utils import temp_filenames
ImportError: cannot import name 'temp_filenames' from 'utils'

How do i go about solving this?

**Comment by adefossez** [comment]
Don't install `utils`, you should uninstall it in fact.

The line that fails should be `from .utils import temp_filenames` not `from utils import temp_filenames` (in master it is the case). Make sure you don't have any modification compared with master, and make sure to run the script for the root of the repository.

**Comment by jaslineljy** [comment]
ah okay noted. Thanks. Can i also check whether if it is possible to evaluate the test set with raw format? because earlier you mention that raw folder expects a folder containing both a `train` and `valid` subfolders but never mention anything about the test set in raw format.

**Comment by adefossez** [comment]
you cannot evaluate the test set with the raw format.

**Comment by jaslineljy** [comment]
Hi, I just want to check whether the raw datasets when being fed into the model, are they divided into smaller pieces? If yes, how many seconds are they broken into for 1 epoch and how to change the split duration?  
I read the papers and look at the code and notice that the MUSDB18 dataset is divided into 11s for each epoch, which can be seen here (if i am not wrong)
```
duration = Fraction(samples + args.data_stride, args.samplerate)
        stride = Fraction(args.data_stride, args.samplerate)
```

**Comment by adefossez** [comment]
Hey guys, now that there is official support for the MusDB-HQ dataset I'm going to close this issue.
