### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by viru05** [facebookresearch/demucs#52]
I have this problem executing that command:

(demucs) bash-3.2$ python3 -m demucs.separate --dl -n demucs /Users/seba/demucs-master/AUDIOS/LongchampsBoogie.m4a 
Illegal instruction: 4
Anyone else with the same problem?
I have usin a MacBook pro.

**Comment by adefossez** [comment]
Related to https://github.com/facebookresearch/demucs/issues/36

@viru05  what version of Mac OS X are you using? What year is your macbook pro from? And how much RAM does it have?
Thanks!

**Comment by CarlosAudio90** [comment]
I have the same problem.
I'm in Yosemite
8 Gb Ram
Mac Pro (mid 2010)
Quad-Core Intel Xeon 3.2 GHz
NVIDIA GeForce GT 120 512 MB

**Comment by adefossez** [comment]
@CarlosAudio90 @viru05 , it seems that this is because your OSX version is too old.
Sadly, I can't do much to help, I'm not sure if this is coming from Anaconda or Pytorch but unless you are willing to recompile all the dependencies it is going to be quite hard to run.

https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

**Comment by viru05** [comment]
> Relacionado con [# 36](https://github.com/facebookresearch/demucs/issues/36)
> 
> @ viru05 ¿qué versión de Mac OS X está utilizando? ¿De qué año es tu MacBook Pro? ¿Y cuánta RAM tiene?
> ¡Gracias!

I have a Macbook Pro 2009 with Sierra 10.12.6 and 8Gb Ram.

**Comment by adefossez** [comment]
@viru05, same I think your version of OSX is too old for either Anaconda or Pytorch :/
