### ISSUE TITLE
Output audio format or quality selection

### ISSUE THREAD

**Issue by fabianmroman** [facebookresearch/demucs#86]
Hello, is there an option to select the quality or format of the separated wav audio files? I am trying to convert externally some of them to MP3 and the files seem to be with too much quality or encoded in some special way and I cannot convert them. 
The command I use is: `python.exe -m demucs.separate -d cpu --dl "PATH_TO_AUDIO_FILE_1"`

Thank you, great job!

**Comment by adefossez** [comment]
Hey @fabianmroman , I think this is because the separate command export as float encoded wav data, rather than int16. I have just pushed a fix so that you can instead use (added an extra `--int16` to activate the new behavior).
`python.exe -m demucs.separate -d cpu --dl --int16 "PATH_TO_AUDIO_FILE_1"`
This should fix your issue. Sorry for the late reply.

**Comment by fabianmroman** [comment]
Great, thank you!
